apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "game-app.fullname" . }}-auth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "game-app.labels" . | nindent 4 }}
    app: {{ include "game-app.fullname" . }}-auth
spec:
  replicas: {{ .Values.auth.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "game-app.fullname" . }}-auth
  template:
    metadata:
      labels:
        app: {{ include "game-app.fullname" . }}-auth
        {{- include "game-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: auth
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ .Values.auth.port }}
          env:
            - name: DB_TYPE
              value: "memory"
            - name: JWT_ISSUER
              value: "play.text2banger.fun"
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "{{ .Values.auth.port }}"
          volumeMounts:
            - name: keys-volume
              mountPath: /app/keys
              readOnly: true
      volumes:
        - name: keys-volume
          secret:
            secretName: auth-keys
