apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "game-app.fullname" . }}-client
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "game-app.labels" . | nindent 4 }}
    app: {{ include "game-app.fullname" . }}-client
spec:
  replicas: {{ .Values.client.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ include "game-app.fullname" . }}-client
  template:
    metadata:
      labels:
        app: {{ include "game-app.fullname" . }}-client
        {{- include "game-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
            - "sh"
            - "-c"
            - "cd /app/dist && npx serve -s . -l {{ .Values.client.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.client.port }}
          env:
            - name: HOST
              value: "0.0.0.0"
            - name: PORT
              value: "{{ .Values.client.port }}"
